Improved Q&A
aws-quickstart/quickstart-discngine-3decision pull request #38
Opened 2022-11-25 15:08 UTC by JonathanManass

Updated documentation Q&A

@vsnyc

2022-12-27 15:28 UTC, vsnyc requested changes
Change requested for minor typos.

2022-12-28 09:50 UTC, JonathanManass commented
changes done @vsync

2022-12-28 19:12 UTC, vsnyc commented
@censullo - could you please review the changes to make sure if follows the AWS Style Guide?

2023-01-12 21:17 UTC, censullo approved these changes

2023-01-12 21:17 UTC, merged